// Code generated by protoc-gen-go. DO NOT EDIT.
// source: colour.proto

package colourgo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Mode int32

const (
	Mode_UNKNOWN_MODE      Mode = 0
	Mode_FREE_FOR_ALL      Mode = 1
	Mode_DEMOCRACY         Mode = 2
	Mode_MARKET            Mode = 3
	Mode_RADICAL_DEMOCRACY Mode = 4
	Mode_RADICAL_MARKET    Mode = 5
)

var Mode_name = map[int32]string{
	0: "UNKNOWN_MODE",
	1: "FREE_FOR_ALL",
	2: "DEMOCRACY",
	3: "MARKET",
	4: "RADICAL_DEMOCRACY",
	5: "RADICAL_MARKET",
}

var Mode_value = map[string]int32{
	"UNKNOWN_MODE":      0,
	"FREE_FOR_ALL":      1,
	"DEMOCRACY":         2,
	"MARKET":            3,
	"RADICAL_DEMOCRACY": 4,
	"RADICAL_MARKET":    5,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}

func (Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b8cfc2a33b1d9e1a, []int{0}
}

type Canvas struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Width                uint32   `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Depth                uint32   `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`
	Mode                 Mode     `protobuf:"varint,5,opt,name=mode,proto3,enum=colour.Mode" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Canvas) Reset()         { *m = Canvas{} }
func (m *Canvas) String() string { return proto.CompactTextString(m) }
func (*Canvas) ProtoMessage()    {}
func (*Canvas) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8cfc2a33b1d9e1a, []int{0}
}

func (m *Canvas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Canvas.Unmarshal(m, b)
}
func (m *Canvas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Canvas.Marshal(b, m, deterministic)
}
func (m *Canvas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Canvas.Merge(m, src)
}
func (m *Canvas) XXX_Size() int {
	return xxx_messageInfo_Canvas.Size(m)
}
func (m *Canvas) XXX_DiscardUnknown() {
	xxx_messageInfo_Canvas.DiscardUnknown(m)
}

var xxx_messageInfo_Canvas proto.InternalMessageInfo

func (m *Canvas) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Canvas) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Canvas) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Canvas) GetDepth() uint32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *Canvas) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_UNKNOWN_MODE
}

type Colour struct {
	Red                  uint32   `protobuf:"varint,1,opt,name=red,proto3" json:"red,omitempty"`
	Green                uint32   `protobuf:"varint,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue                 uint32   `protobuf:"varint,3,opt,name=blue,proto3" json:"blue,omitempty"`
	Alpha                uint32   `protobuf:"varint,4,opt,name=alpha,proto3" json:"alpha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Colour) Reset()         { *m = Colour{} }
func (m *Colour) String() string { return proto.CompactTextString(m) }
func (*Colour) ProtoMessage()    {}
func (*Colour) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8cfc2a33b1d9e1a, []int{1}
}

func (m *Colour) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Colour.Unmarshal(m, b)
}
func (m *Colour) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Colour.Marshal(b, m, deterministic)
}
func (m *Colour) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Colour.Merge(m, src)
}
func (m *Colour) XXX_Size() int {
	return xxx_messageInfo_Colour.Size(m)
}
func (m *Colour) XXX_DiscardUnknown() {
	xxx_messageInfo_Colour.DiscardUnknown(m)
}

var xxx_messageInfo_Colour proto.InternalMessageInfo

func (m *Colour) GetRed() uint32 {
	if m != nil {
		return m.Red
	}
	return 0
}

func (m *Colour) GetGreen() uint32 {
	if m != nil {
		return m.Green
	}
	return 0
}

func (m *Colour) GetBlue() uint32 {
	if m != nil {
		return m.Blue
	}
	return 0
}

func (m *Colour) GetAlpha() uint32 {
	if m != nil {
		return m.Alpha
	}
	return 0
}

type Location struct {
	W                    uint32   `protobuf:"varint,1,opt,name=w,proto3" json:"w,omitempty"`
	X                    uint32   `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    uint32   `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                    uint32   `protobuf:"varint,4,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8cfc2a33b1d9e1a, []int{2}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetW() uint32 {
	if m != nil {
		return m.W
	}
	return 0
}

func (m *Location) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Location) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Location) GetZ() uint32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Vote struct {
	Colour               *Colour   `protobuf:"bytes,1,opt,name=colour,proto3" json:"colour,omitempty"`
	Location             *Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8cfc2a33b1d9e1a, []int{3}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetColour() *Colour {
	if m != nil {
		return m.Colour
	}
	return nil
}

func (m *Vote) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Purchase struct {
	Colour               *Colour   `protobuf:"bytes,1,opt,name=colour,proto3" json:"colour,omitempty"`
	Location             *Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Price                uint32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Tax                  uint32    `protobuf:"varint,4,opt,name=tax,proto3" json:"tax,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Purchase) Reset()         { *m = Purchase{} }
func (m *Purchase) String() string { return proto.CompactTextString(m) }
func (*Purchase) ProtoMessage()    {}
func (*Purchase) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8cfc2a33b1d9e1a, []int{4}
}

func (m *Purchase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Purchase.Unmarshal(m, b)
}
func (m *Purchase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Purchase.Marshal(b, m, deterministic)
}
func (m *Purchase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Purchase.Merge(m, src)
}
func (m *Purchase) XXX_Size() int {
	return xxx_messageInfo_Purchase.Size(m)
}
func (m *Purchase) XXX_DiscardUnknown() {
	xxx_messageInfo_Purchase.DiscardUnknown(m)
}

var xxx_messageInfo_Purchase proto.InternalMessageInfo

func (m *Purchase) GetColour() *Colour {
	if m != nil {
		return m.Colour
	}
	return nil
}

func (m *Purchase) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Purchase) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Purchase) GetTax() uint32 {
	if m != nil {
		return m.Tax
	}
	return 0
}

func init() {
	proto.RegisterEnum("colour.Mode", Mode_name, Mode_value)
	proto.RegisterType((*Canvas)(nil), "colour.Canvas")
	proto.RegisterType((*Colour)(nil), "colour.Colour")
	proto.RegisterType((*Location)(nil), "colour.Location")
	proto.RegisterType((*Vote)(nil), "colour.Vote")
	proto.RegisterType((*Purchase)(nil), "colour.Purchase")
}

func init() { proto.RegisterFile("colour.proto", fileDescriptor_b8cfc2a33b1d9e1a) }

var fileDescriptor_b8cfc2a33b1d9e1a = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xdd, 0x8a, 0xdb, 0x30,
	0x10, 0x85, 0xab, 0x8d, 0x63, 0xb2, 0x93, 0x1f, 0xdc, 0xa1, 0x3f, 0xbe, 0x0c, 0x2e, 0x94, 0x50,
	0x4a, 0x16, 0xd2, 0x27, 0x70, 0x1c, 0x2f, 0x94, 0x38, 0xc9, 0x22, 0xda, 0x2e, 0x5d, 0x0a, 0x41,
	0xb1, 0x45, 0x64, 0x70, 0x22, 0xa3, 0x55, 0x9a, 0xec, 0x5e, 0xf6, 0xaa, 0x8f, 0x5d, 0x24, 0xcb,
	0xed, 0x13, 0xf4, 0x6e, 0xbe, 0xf1, 0xe1, 0xcc, 0x99, 0xb1, 0x60, 0x90, 0xcb, 0x4a, 0x9e, 0xd4,
	0xb4, 0x56, 0x52, 0x4b, 0xf4, 0x1b, 0x8a, 0x7e, 0x11, 0xf0, 0x13, 0x76, 0xfc, 0xc9, 0x1e, 0x11,
	0xc1, 0x3b, 0xb2, 0x03, 0x0f, 0xc9, 0x98, 0x4c, 0xae, 0xa9, 0xad, 0xf1, 0x15, 0x74, 0xcf, 0x65,
	0xa1, 0x45, 0x78, 0x35, 0x26, 0x93, 0x21, 0x6d, 0x00, 0xdf, 0x80, 0x2f, 0x78, 0xb9, 0x17, 0x3a,
	0xec, 0xd8, 0xb6, 0x23, 0xa3, 0x2e, 0x78, 0xad, 0x45, 0xe8, 0x35, 0x6a, 0x0b, 0x38, 0x06, 0xef,
	0x20, 0x0b, 0x1e, 0x76, 0xc7, 0x64, 0x32, 0x9a, 0x0d, 0xa6, 0x2e, 0xc7, 0x4a, 0x16, 0x9c, 0xda,
	0x2f, 0xd1, 0x03, 0xf8, 0x89, 0x6d, 0x62, 0x00, 0x1d, 0xc5, 0x0b, 0x1b, 0x61, 0x48, 0x4d, 0x69,
	0x3c, 0xf7, 0x8a, 0xf3, 0x63, 0x9b, 0xc0, 0x82, 0xc9, 0xba, 0xab, 0x4e, 0xdc, 0xcd, 0xb7, 0xb5,
	0x51, 0xb2, 0xaa, 0x16, 0xac, 0x9d, 0x6e, 0x21, 0x9a, 0x43, 0x2f, 0x93, 0x39, 0xd3, 0xa5, 0x3c,
	0xe2, 0x00, 0xc8, 0xd9, 0x79, 0x93, 0xb3, 0xa1, 0x8b, 0x73, 0x25, 0x17, 0x43, 0x4f, 0xce, 0x8e,
	0x3c, 0x19, 0x7a, 0x76, 0x3e, 0xe4, 0x39, 0xfa, 0x01, 0xde, 0x37, 0xa9, 0x39, 0xbe, 0x07, 0x77,
	0x36, 0x6b, 0xd2, 0x9f, 0x8d, 0xda, 0x5d, 0x9a, 0xf4, 0xd4, 0x7d, 0xc5, 0x8f, 0xd0, 0xab, 0xdc,
	0x4c, 0x3b, 0xa0, 0x3f, 0x0b, 0x5a, 0x65, 0x9b, 0x85, 0xfe, 0x55, 0x44, 0xbf, 0x09, 0xf4, 0xee,
	0x4e, 0x2a, 0x17, 0xec, 0xf1, 0x3f, 0x8d, 0x30, 0xa7, 0xa9, 0x55, 0x99, 0xb7, 0xf7, 0x6a, 0xc0,
	0x1c, 0x5b, 0xb3, 0x8b, 0x5b, 0xd3, 0x94, 0x1f, 0x6a, 0xf0, 0xcc, 0x6f, 0xc1, 0x00, 0x06, 0x5f,
	0xd7, 0xcb, 0xf5, 0xe6, 0x7e, 0xbd, 0x5d, 0x6d, 0x16, 0x69, 0xf0, 0xc2, 0x74, 0x6e, 0x69, 0x9a,
	0x6e, 0x6f, 0x37, 0x74, 0x1b, 0x67, 0x59, 0x40, 0x70, 0x08, 0xd7, 0x8b, 0x74, 0xb5, 0x49, 0x68,
	0x9c, 0x7c, 0x0f, 0xae, 0x10, 0xc0, 0x5f, 0xc5, 0x74, 0x99, 0x7e, 0x09, 0x3a, 0xf8, 0x1a, 0x5e,
	0xd2, 0x78, 0xf1, 0x39, 0x89, 0xb3, 0xed, 0x3f, 0x89, 0x87, 0x08, 0xa3, 0xb6, 0xed, 0xa4, 0xdd,
	0xf9, 0x12, 0xde, 0xe6, 0xf2, 0x30, 0x65, 0x15, 0xd7, 0x82, 0x97, 0xec, 0xcc, 0x14, 0x77, 0x7b,
	0xcc, 0xfb, 0xcd, 0xca, 0x77, 0xe6, 0xbd, 0x3e, 0xbc, 0xdb, 0x97, 0x5a, 0x9c, 0x76, 0xd3, 0x5c,
	0x1e, 0x6e, 0x62, 0x27, 0xbe, 0x67, 0x8a, 0x67, 0x59, 0x72, 0xd3, 0xe8, 0xf7, 0x72, 0xe7, 0xdb,
	0xb7, 0xfd, 0xe9, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x0b, 0xcf, 0xe3, 0xeb, 0x02, 0x00,
	0x00,
}
